pipeline {
    agent {
        label "agent-1"
    }
    options{
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
        //retry(1)
    }
    environment {
        DEBUG = 'true'
        region = 'us-east-1'
        account_id = '752192503692'
        project = 'expense'
        environment = 'dev'
        component = 'mysql'
        
    }

    /* stages {
        
        stage('Docker build') {
            
            steps {
                withAWS(region: "${region}", credentials: 'creds') {
                   sh """
                   cd mysql

                   aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.us-east-1.amazonaws.com

                   docker build -t ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${BUILD_NUMBER} .

                   docker push ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${BUILD_NUMBER}
                   """              }
            }
        } */
       stage('Deploy'){
            steps{
                withAWS(region: 'us-east-1', credentials: 'creds') {
                   sh """
                   aws eks update-kubeconfig --region ${region} --name ${project}

                   cd helm


                   helm upgrade --install ${component} -n ${project} \
                   -f values-${environment}.yaml .
                   """
        }
    }
}
    }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}